all: ./
	g++ -std=c++11 Example.cpp -o ExtenderTest.out -g -I../include -I../include/dependencies/ -I./lib/window-api/include -L./lib/window-api/bin -L../bin -lWindowAPI_D -lTinyExtender -lGL -lX11 2> errors.txt
